language: python

python:
  - 2.7

git:
  depth: 3

install:
  - pip install hap

script:
  - make install
  - cat $HOME/bin/hap
  - export PATH="$HOME/bin:$PATH"
  - hap res/sample.json --verbose --no-cache
  - ls -lahR $HOME/.hap
  - hap register res/sample.json
  - hap dataplans
  - hap check sample.json http://skyle.codeissues.net/
  - hap join sample.json http://skyle.codeissues.net/
  - ls -lahR $HOME/.hap
  - hap dump http://skyle.codeissues.net/
  - hap jobs
  - hap pause http://skyle.codeissues.net/
  - hap jobs
  - hap resume http://skyle.codeissues.net/
  - hap jobs
  - hap purge http://skyle.codeissues.net/
  - hap jobs
  - echo y | hap unregister sample.json
  - cat $(ls *.tsv)
  - ls -lahR $HOME/.hap
  - cat $HOME/.hap/.log
